import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

const images = ["/og/rN3.jpg", "/og/woman-in-the-wind.jpg", "/og/zionn2.jpg"];

const Home: NextPage = () => {
  const [currentImageIndex, setCurrentImageIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImageIndex((prevIndex) => (prevIndex + 1) % images.length);
    }, 5000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Sarae Photography</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative">
        <div className="flex h-screen w-screen items-center justify-center">
          {images.map((imageUrl, index) => (
            <Image
              key={index}
              src={imageUrl ?? ""}
              alt="Landing page background"
              className={`absolute h-full w-full object-cover transition-opacity duration-2000 ${
                index === currentImageIndex ? "opacity-100" : "opacity-0"
              }`}
              width={6000}
              height={4000}
            ></Image>
          ))}
          <div className="z-10">
            <Link href={`/gallery`} className="text-slate-100 hover:text-white">
              <h1 className="animate-fade-in-slow text-center text-6xl">
                Sarae Photography
              </h1>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
