import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

import fs from "fs";
import path from "path";

interface HomeProps {
  images: string[];
}
const Home: NextPage<HomeProps> = ({ images }) => {
  const [currentImageIndex, setCurrentImageIndex] = useState<number>(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImageIndex((prevIndex) => (prevIndex + 1) % images.length);
    }, 5000);

    return () => {
      clearInterval(interval);
    };
  }, [images.length]);

  return (
    <>
      <Head>
        <title>Sarae Photography</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative">
        <div className="flex h-screen w-screen items-center justify-center">
          {images.map((imageUrl, index) => (
            <Image
              key={index}
              src={`/og/${imageUrl}` ?? ""}
              alt="Landing page background"
              className={`absolute h-full w-full object-cover transition-opacity duration-2000 ${
                index === currentImageIndex ? "opacity-100" : "opacity-0"
              }`}
              width={6000}
              height={4000}
            />
          ))}
          <div className="z-10">
            <Link href={`/gallery`} className="hover:opacity-75">
              <h1 className="animate-fade-in-medium text-center text-5xl">
                Sarae Photography
              </h1>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<HomeProps> = () => {
  const imageDirectory = path.join(process.cwd(), "public", "og");
  const images = fs.readdirSync(imageDirectory);

  return {
    props: {
      images,
    },
  };
};

export default Home;
